-- MySQL Script generated by MySQL Workbench
-- Sun Oct  4 03:30:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rencontres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rencontres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rencontres` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `rencontres` ;

-- -----------------------------------------------------
-- Table `rencontres`.`forums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rencontres`.`forums` (
  `idforums` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `idmembre` INT NOT NULL,
  `idmetier` INT NOT NULL,
  PRIMARY KEY (`idforums`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rencontres`.`membres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rencontres`.`membres` (
  `idmembres` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NULL,
  `forums_idforums` INT NOT NULL,
  PRIMARY KEY (`idmembres`, `forums_idforums`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telephone_UNIQUE` (`telephone` ASC) VISIBLE,
  INDEX `fk_membres_forums1_idx` (`forums_idforums` ASC) VISIBLE,
  CONSTRAINT `fk_membres_forums1`
    FOREIGN KEY (`forums_idforums`)
    REFERENCES `rencontres`.`forums` (`idforums`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rencontres`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rencontres`.`services` (
  `idservices` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `idmetier` INT NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `type_services` VARCHAR(45) NULL,
  `idmembre` INT NOT NULL,
  `membres_idmembres` INT NOT NULL,
  `membres_forums_idforums` INT NOT NULL,
  PRIMARY KEY (`idservices`, `membres_idmembres`, `membres_forums_idforums`),
  INDEX `fk_services_membres1_idx` (`membres_idmembres` ASC, `membres_forums_idforums` ASC) VISIBLE,
  CONSTRAINT `fk_services_membres1`
    FOREIGN KEY (`membres_idmembres` , `membres_forums_idforums`)
    REFERENCES `rencontres`.`membres` (`idmembres` , `forums_idforums`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rencontres`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rencontres`.`messages` (
  `idmessages` INT NOT NULL AUTO_INCREMENT,
  `idforums` INT NULL,
  `idmembres` INT NULL,
  `contenu` VARCHAR(255) NULL,
  `forums_idforums` INT NOT NULL,
  PRIMARY KEY (`idmessages`, `forums_idforums`),
  INDEX `fk_messages_forums1_idx` (`forums_idforums` ASC) VISIBLE,
  CONSTRAINT `fk_messages_forums1`
    FOREIGN KEY (`forums_idforums`)
    REFERENCES `rencontres`.`forums` (`idforums`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rencontres`.`reponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rencontres`.`reponses` (
  `idreponses` INT NOT NULL AUTO_INCREMENT,
  `idmessages` INT NULL,
  `contenu` VARCHAR(255) NOT NULL,
  `messages_idmessages` INT NOT NULL,
  PRIMARY KEY (`idreponses`, `messages_idmessages`),
  INDEX `fk_reponses_messages_idx` (`messages_idmessages` ASC) VISIBLE,
  CONSTRAINT `fk_reponses_messages`
    FOREIGN KEY (`messages_idmessages`)
    REFERENCES `rencontres`.`messages` (`idmessages`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rencontres`.`metiers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rencontres`.`metiers` (
  `idmetiers` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `forums_idforums` INT NOT NULL,
  PRIMARY KEY (`idmetiers`, `forums_idforums`),
  INDEX `fk_metiers_forums1_idx` (`forums_idforums` ASC) VISIBLE,
  CONSTRAINT `fk_metiers_forums1`
    FOREIGN KEY (`forums_idforums`)
    REFERENCES `rencontres`.`forums` (`idforums`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rencontres`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rencontres`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;

USE `rencontres` ;

-- -----------------------------------------------------
-- Placeholder table for view `rencontres`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rencontres`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `rencontres`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rencontres`.`view1`;
USE `rencontres`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
